import type { Metadata } from "next";
import { Poppins, Roboto_Flex } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/auth/SessionWrapper";
import Nav from "@/components/Nav";
import { Toaster } from "react-hot-toast";

const robotoFlex = Roboto_Flex({
  weight: "variable",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFlex.className} antialiased`}
      >
        <SessionWrapper>
          <Nav />
          <Toaster containerClassName="mt-[8vh]" position="top-right" />
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
