name: revive aiven

on:
  schedule:
    - cron: '0 9 * * 1' 

jobs:
  ping-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Ping Aiven Postgres
        env:
          DATABASE_URL: ${{ secrets.AIVEN_DATABASE_URL }}
        run: |
          echo "SELECT 1;" | psql "$DATABASE_URL"
